# Generated by Django 5.0.1 on 2024-01-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_order_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='appear',
            field=models.BooleanField(default=True),
        ),
    ]
