# Generated by Django 5.0.1 on 2024-01-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_pet_appear'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
